### ISSUE TITLE
Zoom speed is a bit too powerful

### ISSUE THREAD

**Issue by M1kep** [badarsebard/terraforge#1]
Currently if you zoom out too quickly you can very easily lose all of your resources. Possibly slow down the scroll speed, or provide some way to recenter the view

**Comment by badarsebard** [comment]
Working on a fix for this. There's a cytoscape extension that adds pam/zoom controls as well as a button that will center and zoom all contents into the view port.

**Comment by badarsebard** [comment]
This is resolved by `e8ebd24a1123898e75d43897b3208be1ef3aa1cb`.
